name: Fancrew Monitor Checker

on:
  schedule:
    - cron: "*/15 * * * *"  # 15分ごと
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run monitor check
        run: python check_monitor.py
